const AURORA_DEFAULT_DATA = {
  "version": 19,
  "settings": {
    "name": "Ateliê Verônica Rodrigues",
    "tagline": "Bolos e doces personalizados",
    "logo": "products/logo-pink.png",
    "banner": "products/foto-hero-redvelvet.jpg",
    "sobreImage": "products/foto-veronica-historia.jpg",
    "whatsapp": "5537998741557",
    "instagram": "https://www.instagram.com/veronicabolospiumhi",
    "instagramUser": "@veronicabolospiumhi",
    "facebook": "",
    "email": "",
    "address": "Rua Padre Francisco Goulart, 610 — Bairro Novo Horizonte 2",
    "hours": "Pedidos pelo WhatsApp",
    "deliveryFee": 5,
    "deliveryNote": "Bairros mais afastados: consultar",
    "followers": "",
    "posts": "",
    "mapEmbed": "",
    "heroBadge": "Ateliê de bolos e doces personalizados",
    "heroStory": [],
    "sobreText1": "Meu nome é Verônica Rodrigues e o Ateliê nasceu em 2021, em meio à pandemia, quando uma oportunidade para complementar a renda se transformou na maior paixão da minha vida. Em pouco tempo, descobri que a confeitaria era o meu propósito e decidi investir em conhecimento para oferecer sempre o melhor aos meus clientes.",
    "sobreText2": "Cada desafio que enfrentei me tornou mais forte e reforçou a certeza de que os sonhos se constroem com dedicação, amor e perseverança. Hoje, cada bolo, fatia e doce que preparo é feito com carinho, como se fosse para a minha própria família. Meu maior desejo é que cada cliente se sinta abraçado, amado e lembrado em um dos momentos mais especiais da vida. Seja bem-vindo ao Ateliê Verônica Rodrigues, onde cada receita é feita para adoçar a sua história."
  },
  "auth": {
    "email": "admin@veronica.com",
    "password": "veronica123"
  },
  "categories": [
    { "id": "cat-bolos", "name": "Bolos", "slug": "bolos" },
    { "id": "cat-copos", "name": "Copos da Felicidade", "slug": "copos" },
    { "id": "cat-fatias", "name": "Fatias", "slug": "fatias" }
  ],
  "products": [
    {
      "id": "p-ninho-nutella",
      "name": "Bolo de Ninho com Nutella",
      "description": "Bolo de leite ninho com recheio generoso de Nutella.",
      "price": 25,
      "categoryId": "cat-bolos",
      "image": "products/bolo-baunilha.png",
      "featured": true,
      "slug": "bolo-ninho-com-nutella",
      "size": "",
      "flavors": [],
      "promoActive": false,
      "promoPrice": null,
      "promoLabel": "",
      "bestSeller": true,
      "active": true
    },
    {
      "id": "p-ninho-morango",
      "name": "Bolo Ninho, Morango e Suspiro",
      "description": "Bolo de leite ninho com morango fresco e suspiro crocante.",
      "price": 25,
      "categoryId": "cat-bolos",
      "image": "products/foto-bolo-morango.jpg",
      "featured": true,
      "slug": "bolo-ninho-morango-suspiro",
      "size": "",
      "flavors": [],
      "promoActive": false,
      "promoPrice": null,
      "promoLabel": "",
      "bestSeller": true,
      "active": true
    },
    {
      "id": "p-ferrero",
      "name": "Bolo Ferrero Rocher",
      "description": "Bolo Ferrero Rocher — chocolate, avelã e crocante.",
      "price": 25,
      "categoryId": "cat-bolos",
      "image": "products/foto-bolo-kinder.jpg",
      "featured": true,
      "slug": "bolo-ferrero-rocher",
      "size": "",
      "flavors": [],
      "promoActive": false,
      "promoPrice": null,
      "promoLabel": "",
      "bestSeller": true,
      "active": true
    },
    {
      "id": "p-limao-siciliano",
      "name": "Bolo Limão Siciliano com Frutas Vermelhas",
      "description": "Bolo de limão siciliano com frutas vermelhas.",
      "price": 25,
      "categoryId": "cat-bolos",
      "image": "products/bolo-limao.png",
      "featured": true,
      "slug": "bolo-limao-siciliano-frutas-vermelhas",
      "size": "",
      "flavors": [],
      "promoActive": false,
      "promoPrice": null,
      "promoLabel": "",
      "bestSeller": true,
      "active": true
    },
    {
      "id": "p-copo-maracuja",
      "name": "Copo da Felicidade — Maracujá Trufado com Musse de Chocolate",
      "description": "Copo da felicidade com brigadeiro de maracujá trufado e musse de chocolate.",
      "price": 18,
      "categoryId": "cat-copos",
      "image": "products/bolo-brownie-drip.png",
      "featured": true,
      "slug": "copo-felicidade-maracuja-musse-chocolate",
      "size": "",
      "flavors": [],
      "promoActive": false,
      "promoPrice": null,
      "promoLabel": "",
      "bestSeller": true,
      "active": true
    },
    {
      "id": "p-copo-pudim",
      "name": "Copo da Felicidade — Pudim",
      "description": "Copo da felicidade com pudim cremoso de caramelo.",
      "price": 22,
      "categoryId": "cat-copos",
      "image": "products/pote-pudim.png",
      "featured": true,
      "slug": "copo-felicidade-pudim",
      "size": "",
      "flavors": [],
      "promoActive": false,
      "promoPrice": null,
      "promoLabel": "",
      "bestSeller": true,
      "active": true
    },
    {
      "id": "p-fatia-chocobrownie",
      "name": "Fatia de Chocobrownie",
      "description": "Fatia de chocobrownie — chocolate intenso e textura fudgy.",
      "price": 25,
      "categoryId": "cat-fatias",
      "image": "products/foto-chocobrownie.jpg",
      "featured": true,
      "slug": "fatia-chocobrownie",
      "size": "fatia",
      "flavors": ["Calda caramelo", "Calda de chocolate", "Calda de ninho"],
      "promoActive": false,
      "promoPrice": null,
      "promoLabel": "",
      "bestSeller": true,
      "active": true
    },
    {
      "id": "p-fatia-brigadeiro-maracuja",
      "name": "Fatia de Brigadeiro com Maracujá Trufado",
      "description": "Fatia de brigadeiro com maracujá trufado.",
      "price": 25,
      "categoryId": "cat-fatias",
      "image": "products/foto-bolo-maracuja.jpg",
      "featured": true,
      "slug": "fatia-brigadeiro-maracuja-trufado",
      "size": "fatia",
      "flavors": ["Calda caramelo", "Calda de chocolate", "Calda de ninho"],
      "promoActive": false,
      "promoPrice": null,
      "promoLabel": "",
      "active": true
    },
    {
      "id": "p-fatia-palha",
      "name": "Fatia de Palha Italiana",
      "description": "Fatia de palha italiana clássica.",
      "price": 25,
      "categoryId": "cat-fatias",
      "image": "products/bolo-chocolate.png",
      "featured": true,
      "slug": "fatia-palha-italiana",
      "size": "fatia",
      "flavors": ["Calda caramelo", "Calda de chocolate", "Calda de ninho"],
      "promoActive": false,
      "promoPrice": null,
      "promoLabel": "",
      "active": true
    },
    {
      "id": "p-fatia-oreo",
      "name": "Fatia de Oreo",
      "description": "Fatia de Oreo — cookies & cream.",
      "price": 25,
      "categoryId": "cat-fatias",
      "image": "products/bolo-oreo.png",
      "featured": true,
      "slug": "fatia-oreo",
      "size": "fatia",
      "flavors": ["Calda caramelo", "Calda de chocolate", "Calda de ninho"],
      "promoActive": false,
      "promoPrice": null,
      "promoLabel": "",
      "bestSeller": true,
      "active": true
    },
    {
      "id": "p-fatia-matilda",
      "name": "Fatia Matilda",
      "description": "Fatia Matilda — chocolate cremoso e marcante.",
      "price": 25,
      "categoryId": "cat-fatias",
      "image": "products/bolo-chocolate-camadas.png",
      "featured": true,
      "slug": "fatia-matilda",
      "size": "fatia",
      "flavors": ["Calda caramelo", "Calda de chocolate", "Calda de ninho"],
      "promoActive": false,
      "promoPrice": null,
      "promoLabel": "",
      "bestSeller": true,
      "active": true
    },
    {
      "id": "p-fatia-ouro-branco",
      "name": "Fatia de Ouro Branco",
      "description": "Fatia de Ouro Branco — chocolate branco cremoso.",
      "price": 25,
      "categoryId": "cat-fatias",
      "image": "products/foto-bolo-ninho.jpg",
      "featured": true,
      "slug": "fatia-ouro-branco",
      "size": "fatia",
      "flavors": ["Calda caramelo", "Calda de chocolate", "Calda de ninho"],
      "promoActive": false,
      "promoPrice": null,
      "promoLabel": "",
      "active": true
    }
  ],
  "clients": [],
  "orders": [],
  "reviews": [],
  "faq": [],
  "gallery": [
    "products/foto-veronica-vitrine.jpg",
    "products/foto-hero-redvelvet.jpg",
    "products/foto-bolo-kinder.jpg",
    "products/foto-bolo-morango.jpg",
    "products/foto-bolo-ninho.jpg",
    "products/foto-chocobrownie.jpg",
    "products/foto-bolo-pudim.jpg",
    "products/foto-bolo-maracuja.jpg",
    "products/foto-bolo-chocolate-nuts.jpg",
    "products/foto-veronica-feira.jpg"
  ],
  "finance": []
};
